In [1]:
import sys
import os
sys.path.insert(0, os.path.abspath('..'))

In [2]:
from maddux.robots import Link, Arm
from maddux.robots import create_simple_human_arm
from maddux.robots import utils
import numpy as np

In [3]:
q0 = np.array([0, np.pi/4, 0, -np.pi/4, np.pi/2])
human_arm = create_simple_human_arm(2.0, 1.0, q0)

0
[ 0.  0.  0.]
[ 0.  0.  0.]
0.0
0
[ 0.  0.  0.]
[ 0.  0.  0.]
0.0
2.0
[ 0.  0.  0.]
[[ 0.  0.  0.]]
0.0
0
[[ 0.  0.  0.]]
[[ 0.  0.  0.]]
0.0
1.0
[[ 0.  0.  0.]]
[[  1.41421356e+00  -2.88037407e-04   1.41421353e+00]]
2.0


In [4]:
# human_arm.ikine(np.array([1,1,1]), 10000, 0.01)

In [5]:
config = human_arm.fkine(q=np.array([0, np.pi/4, 0, -np.pi/4, np.pi/2]), links=[0, 1, 2])

In [6]:
np.linalg.norm(utils.create_point_from_homogeneous_transform(config))

2.0

In [7]:
human_arm.get_current_joint_config()

array([ 0.        ,  0.78539816,  0.        , -0.78539816,  1.57079633])

In [8]:
for link in human_arm.links:
    print link.base_pos
    print link.end_pos
    print

[ 0.  0.  0.]
[ 0.  0.  0.]

[ 0.  0.  0.]
[ 0.  0.  0.]

[ 0.  0.  0.]
[[ 0.  0.  0.]]

[[ 0.  0.  0.]]
[[ 0.  0.  0.]]

[[ 0.  0.  0.]]
[[  1.41421356e+00  -2.88037407e-04   1.41421353e+00]]



In [9]:
config

matrix([[  7.07106781e-01,   7.07106723e-01,   2.88037401e-04,
           1.41421356e+00],
        [ -1.44018703e-04,  -2.63327699e-04,   9.99999955e-01,
          -2.88037407e-04],
        [  7.07106767e-01,  -7.07106791e-01,  -8.43642082e-05,
           1.41421353e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           1.00000000e+00]])

In [20]:
human_arm.links[3].base_pos.A1

array([ 0.,  0.,  0.])